version = 1

test_patterns = [
  "src/**",
  "test/**"
]

exclude_patterns = [
  ".release-it.js",
  "commitlint.config.ts"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["vitest"]