#:schema node_modules/wrangler/config-schema.json
name = "short"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Copy this file to wrangler.toml and uncomment the following block if you dont use github actions

# [vars]
# AUTH_SECRET = "production_value"

# [[kv_namespaces]]
# binding = "SHORT_URLS"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

