# Copyright (c) 2025 Joshua Schmitt
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/jqshuv/short/discussions/categories/q-a
    about: Please ask and answer questions here.
