name: 🖊️ Check diff API documentation

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/api-docs.yaml'
      - '.github/workflows/bump.yml'

jobs:
  api-diff:
    if: github.repository == 'jqshuv/short'
    name: 🤖 Check API diff
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
      - name: 🖊️ Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: short
          hub: jqshuv
          token: ${{ secrets.BUMPSH_SECRET }}
          file: docs/api-docs.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


